import Head from "next/head";
import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.sass";
import { HomePage } from "@/components/home/home-page";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <div>
        <Head>
          <title>Events App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <HomePage data={data} />
      </div>
    </>
  );
}

// here we're use serverside props and up above we're destructing our props so it can grab said prop directly. its all so we can render content server side. this will get ran first before it runs the rest of the components. we can also add a key or a secret where the client itself wont have access to any private info.
export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
// THIS IS OUR HOME PAGE
